name: unittest
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    name: Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install apt dependencies
        run: sudo apt update && sudo apt install -y libcurl4-openssl-dev libssl-dev libjpeg-dev
      - name: Install pip dependencies
        run: make setup
      - run: make test
